networks:
  my_network:
    driver: bridge

services:
  server:
    build:
      dockerfile: ./Server.dockerfile
    container_name: server
    tty: true
    stdin_open: true
    volumes:
      - ./server:/server
    ports:
      - "8501:8501" # Optional, to access it outside the network
    networks:
      - my_network
    depends_on:
      - registry

  client:
    build:
      dockerfile: ./Client.dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ./client:/client
    networks:
      - my_network
    working_dir: "/client"

  registry:
    build:
      dockerfile: ./Registry.dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ./registry:/resgistry
    networks:
      - my_network
    working_dir: "/registry"
