networks:
  dissertation_network:
    driver: bridge
    name: dissertation_network

services:
  optimizer:
    build:
      dockerfile: ./docker/optimizer.dockerfile
    tty: true
    stdin_open: true
    networks:
      - dissertation_network
    volumes:
      - ./Optimizer:/src/Optimizer
      - ./proto_compiled:/src/proto_compiled
      - ./Main/OptimizerMain.py:/src/Main.py
      - ./start.sh:/src/start.sh

      - ./Other/models:/optimizer_data/models
      - ./Other/models_profiles:/optimizer_data/models_profiles
      - ./Other/divided_models:/optimizer_data/divided_models
      - ./Other/plans/:/optimizer_data/plans
    working_dir: /src

  registry:
    build:
      dockerfile: ./docker/registry.dockerfile
    tty: true
    stdin_open: true
    networks:
      - dissertation_network
    volumes:
      - ./proto_compiled:/src/proto_compiled
      - ./Registry:/src/Registry
      - ./StatePool:/src/StatePool
      - ./Main/RegistryMain.py:/src/Main.py
      - ./start.sh:/src/start.sh
    working_dir: /src

  server:
    build:
      dockerfile: ./docker/server.dockerfile
    tty: true
    stdin_open: true
    networks:
      - dissertation_network
    volumes:
      - ./Server:/src/Server
      - ./CommonServer:/src/CommonServer
      - ./proto_compiled:/src/proto_compiled
      - ./Main/ServerMain.py:/src/Main.py
      - ./start.sh:/src/start.sh
    working_dir: /src

  client:
    build:
      dockerfile: ./docker/server.dockerfile
    tty: true
    stdin_open: true
    networks:
      - dissertation_network
    volumes:
      - ./Client:/src/Client
      - ./Server:/src/Server
      - ./FrontEnd:/src/FrontEnd
      - ./CommonServer:/src/CommonServer
      - ./proto_compiled:/src/proto_compiled

      - ./Main/ServerMain.py:/src/ServerMain.py
      - ./Main/FrontEndMain.py:/src/FrontEndMain.py
      - ./Main/ClientMain.py:/src/ClientMain.py

      - ./start.sh:/src/start.sh
    working_dir: /src

  pool:
    build:
      dockerfile: ./docker/pool.dockerfile
    tty: true
    stdin_open: true
    networks:
      - dissertation_network
    volumes:
      - ./ModelPool:/src/ModelPool
      - ./proto_compiled:/src/proto_compiled
      - ./Main/ModelPoolMain.py:/src/Main.py
      - ./start.sh:/src/start.sh
    working_dir: /src

  # edge:
  #   build:
  #     dockerfile: ./docker/edge.dockerfile
  #   tty: true
  #   stdin_open: true
  #   networks:
  #     - sdcc_network
  #   volumes:
  #     - type: tmpfs
  #       target: /files
  #       tmpfs:
  #         size: 100M ## Va per pagine di memoria principale (4k)
  #     - ./edge:/src
  #     - ./proto:/proto
  #     # - ./docker/edge_files:/files
  #     - ./docker/aws:/aws
  #   working_dir: /src
  #   deploy:
  #     resources:
  #       limits: # Hard Limit
  #         cpus: "1"
  #         memory: 2G
  #       # reservations: # Soft Limit
  #       #   cpus: 0.25
  #       #   memory: 128M
