networks:
  dissertation_network:
    driver: bridge
    name: dissertation_network

services:
  optimizer:
    build:
      dockerfile: ./docker/optimizer.dockerfile
    tty: true
    stdin_open: true
    networks:
      - dissertation_network
    volumes:
      - ./proto_compiled:/src/proto_compiled

      - ./Optimizer:/src/Optimizer

      - ./Main/OptimizerMain.py:/src/Main.py
      - ./start.sh:/src/start.sh
      - ./config/local_config.ini:/src/config/config.ini

      - ./Common:/src/Common
      - ./CommonProfile:/src/CommonProfile
      - ./CommonPlan:/src/CommonPlan

      - ./Other/models_profiles:/optimizer_data/models_profiles
      - ./Other/plans/:/optimizer_data/plans
    working_dir: /src

  deployer:
    build:
      dockerfile: ./docker/optimizer.dockerfile
    tty: true
    stdin_open: true
    networks:
      - dissertation_network
    volumes:
      - ./proto_compiled:/src/proto_compiled

      - ./Deployer:/src/Deployer

      - ./Main/DeployerMain.py:/src/Main.py
      - ./start.sh:/src/start.sh
      - ./config/local_config.ini:/src/config/config.ini

      - ./Common:/src/Common
      - ./CommonProfile:/src/CommonProfile
      - ./CommonPlan:/src/CommonPlan
    working_dir: /src

  registry:
    build:
      dockerfile: ./docker/registry.dockerfile
    tty: true
    stdin_open: true
    networks:
      - dissertation_network
    volumes:
      - ./proto_compiled:/src/proto_compiled

      - ./Registry:/src/Registry
      - ./StatePool:/src/StatePool

      - ./Main/RegistryMain.py:/src/Main.py
      - ./start.sh:/src/start.sh
      - ./config/local_config.ini:/src/config/config.ini

      - ./Common:/src/Common
    working_dir: /src

  server:
    build:
      dockerfile: ./docker/server.dockerfile
    tty: true
    stdin_open: true
    networks:
      - dissertation_network
    volumes:
      - ./proto_compiled:/src/proto_compiled

      - ./Server:/src/Server

      - ./Main/ServerMain.py:/src/Main.py
      - ./start.sh:/src/start.sh
      - ./config/local_config.ini:/src/config/config.ini

      - ./CommonServer:/src/CommonServer
      - ./Common:/src/Common
      - ./CommonModel:/src/CommonModel
      - ./CommonProfile:/src/CommonProfile

      - ./Other/latency_scripts/delay_script.py:/root/delay_script.py
    working_dir: /src
    cap_add:
      - NET_ADMIN
    deploy:
      resources:
        limits: # Hard Limit
          cpus: "3"
          memory: 6G

  client:
    build:
      dockerfile: ./docker/server.dockerfile
    tty: true
    stdin_open: true
    networks:
      - dissertation_network
    volumes:
      - ./proto_compiled:/src/proto_compiled

      - ./Client:/src/Client
      - ./Server:/src/Server
      - ./FrontEnd:/src/FrontEnd

      - ./Main/ServerMain.py:/src/ServerMain.py
      - ./Main/FrontEndMain.py:/src/FrontEndMain.py
      - ./Main/ClientMain.py:/src/ClientMain.py
      - ./start.sh:/src/start.sh
      - ./config/local_config.ini:/src/config/config.ini

      - ./CommonServer:/src/CommonServer
      - ./Common:/src/Common

      - ./Other/latency_scripts/delay_script.py:/root/delay_script.py
    working_dir: /src
    cap_add:
      - NET_ADMIN
    deploy:
      resources:
        limits: # Hard Limit
          cpus: "0.5"
          memory: 2G

  model_manager:
    build:
      dockerfile: ./docker/manager.dockerfile
    tty: true
    stdin_open: true
    networks:
      - dissertation_network
    volumes:
      - ./proto_compiled:/src/proto_compiled

      - ./ModelPool:/src/ModelPool
      - ./ModelDivider:/src/ModelDivider
      - ./ModelProfiler:/src/ModelProfiler

      - ./Main/ModelManagerMain.py:/src/Main.py
      - ./start.sh:/src/start.sh
      - ./config/local_config.ini:/src/config/config.ini

      - ./Common:/src/Common
      - ./CommonProfile:/src/CommonProfile
      - ./CommonPlan:/src/CommonPlan
      - ./CommonModel:/src/CommonModel

      - ./Other/models:/model_pool_data/models
      - ./Other/models_profiles:/model_profiler_data/models_profiles
      - ./Other/divided_models:/model_pool_data/components
      - ./Other/calibration_dataset:/model_pool_data/calibration_dataset

    working_dir: /src
