networks:
  dissertation_network:
    driver: bridge
    name: dissertation_network

services:
  # client:
  #   build:
  #     dockerfile: ./docker/client.dockerfile
  #   tty: true
  #   stdin_open: true
  #   volumes:
  #     - ./client:/src
  #     - ./proto:/proto
  #     - ./docker/client_files:/files
  #     - ./test/Results:/Results
  #     - ./docker/aws:/.aws
  #   networks:
  #     - sdcc_network
  #   working_dir: /src

  optimizer:
    build:
      dockerfile: ./docker/optimizer.dockerfile
    tty: true
    stdin_open: true
    networks:
      - dissertation_network
    volumes:
      - ./Optimizer:/src
      - ./Optimizer/models:/optimizer_data/models
      - ./Optimizer/model_profiles:/optimizer_data/model_profiles
    working_dir: /src

  registry:
    build:
      dockerfile: ./docker/registry.dockerfile
    tty: true
    stdin_open: true
    networks:
      - dissertation_network
    volumes:
      - ./Registry:/src
    working_dir: /src

  server:
    build:
      dockerfile: ./docker/server.dockerfile
    tty: true
    stdin_open: true
    networks:
      - dissertation_network
    volumes:
      - ./Server:/src
    working_dir: /src

  frontend:
    build:
      dockerfile: ./docker/server.dockerfile
    tty: true
    stdin_open: true
    networks:
      - dissertation_network
    volumes:
      - ./FrontEnd:/src
    working_dir: /src

  # load_balancer:
  #   build:
  #     dockerfile: ./docker/load_balancer.dockerfile
  #   tty: true
  #   stdin_open: true
  #   networks:
  #     - sdcc_network
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - ./load_balancer:/src
  #     - ./proto/load_balancer:/proto

  # edge:
  #   build:
  #     dockerfile: ./docker/edge.dockerfile
  #   tty: true
  #   stdin_open: true
  #   networks:
  #     - sdcc_network
  #   volumes:
  #     - type: tmpfs
  #       target: /files
  #       tmpfs:
  #         size: 100M ## Va per pagine di memoria principale (4k)
  #     - ./edge:/src
  #     - ./proto:/proto
  #     # - ./docker/edge_files:/files
  #     - ./docker/aws:/aws
  #   working_dir: /src
  #   deploy:
  #     resources:
  #       limits: # Hard Limit
  #         cpus: "1"
  #         memory: 2G
  #       # reservations: # Soft Limit
  #       #   cpus: 0.25
  #       #   memory: 128M
